### ISSUE TITLE
Default repos url isn't actually overridden for turtlebot demo.

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2/ci#56]
Despite an alternate [default_repos_url being set](https://github.com/ros2/ci/blob/ac7ec89e398d0afcc879dc38840dad7bc264e3dc/create_jenkins_job.py#L198) for the turtlebot CI job, the regular ros2.repos file is [still being used](http://ci.ros2.org/job/ci_turtlebot-demo/9/consoleFull#console-section-7) unless an alternate repos file is specified as a parameter.

I traced this issue to [ros2_batch_job](https://github.com/ros2/ci/blob/ac7ec89e398d0afcc879dc38840dad7bc264e3dc/ros2_batch_job/__main__.py#L34) which uses the constant `DEFAULT_REPOS_URL` rather than any job-specific data to set a default repos url.

**Comment by nuclearsandwich** [comment]
The possible resolutions I see for this are (in no order) 

* Making the `DEFAULT_REPOS_URL` a dict keyed on the job type (with a fallback to the default default).
* Explicitly setting the `CI_ROS2_REPOS_URL` environment variable for jobs with custom default repos files.
* Changing the ros2_batch_job to pull the default repos file from the job configuration instead of supplying it as a constant. (Moving the current constant to the job creation script where it can be overridden)

None of those three stands out as an optimal solution and the first seems super duper hacky.

I am somewhat inclined to leave this as a wontfix for now since the workaround of supplying an explicit repos url parameter is straightforward and next on my buildfarm todo list is to actually revert this custom default repos url behavior in favor of a supplementary repos file which updates the default at runtime rather than totally replaces it.

**Comment by dhood** [comment]
The DEFAULT_REPOS_URL is being used just if another url isn't specified using [the `--repo-file-url`](https://github.com/ros2/ci/blob/ac7ec89e398d0afcc879dc38840dad7bc264e3dc/ros2_batch_job/__main__.py#L86).

The associated variable after argument parsing with `argparse` (by default) has underscores instead of hyphens: [this is where it's being used](https://github.com/ros2/ci/blob/ac7ec89e398d0afcc879dc38840dad7bc264e3dc/ros2_batch_job/__main__.py#L394)

I think what we need to do is [call the python script](https://github.com/ros2/ci/blob/aee919f402cab3e87e7dadcefe854c4e07466dcb/job_templates/ci_job.xml.em#L269) with the additional `--repo-file-url`. If we also specify [this value](https://github.com/ros2/ci/blob/aee919f402cab3e87e7dadcefe854c4e07466dcb/job_templates/ci_job.xml.em#L134) in [this script](https://github.com/ros2/ci/blob/master/create_jenkins_job.py#L198) I think it should get passed through correctly. (the default being specified is just updating the description of the jenkins job atm)

**Comment by nuclearsandwich** [comment]
> I think what we need to do is call the python script with the additional --repo-file-url. If we also specify this value in this script I think it should get passed through correctly. (the default being specified is just updating the description of the jenkins job atm)

This seems like the entirely sensible fix I was looking for and couldn't find. Thanks! With that in mind it seems reasonable to fix it while the supplementary repo work is underway. Especially since it'll avoid this issue if we ever do want an alternative default repos file.
