### ISSUE TITLE
Docker image for windows

### ISSUE THREAD

**Issue by anacsousa1** [ros2/ci#576]
Hi,

I've started looking into CI for my projects. I'm interested in using a docker image and build-test some packages there. I can run ROS2 nodes in docker (http://docs.ros.org.ros.informatik.uni-freiburg.de/en/foxy/Guides/Run-2-nodes-in-single-or-separate-docker-containers.html). However, I notice that the docker image is for Ubuntu. I couldn't find one for windows; if there is one, where can I find it?

If possible, could someone help me with a simple guide for beginners in the CI world? I've successfully tried some simple tutorials with Travis CI, but I wanted to add my ros2 packages as well. Some are developed in Ubuntu, but others in Windows. I've also noticed that you use Jenkins. If it is easier, I'm glad to test there, of course.

Any help is appreciated.

**Comment by nuclearsandwich** [comment]
> However, I notice that the docker image is for Ubuntu. I couldn't find one for windows; if there is one, where can I find it?

We don't currently provide Docker images for Windows. If you want to create your own Windows Docker images you can look at our CI which uses a chef cookbook within the Docker image for inspiration https://github.com/ros2/ci/blob/master/windows_docker_resources/Dockerfile

> If possible, could someone help me with a simple guide for beginners in the CI world? I've successfully tried some simple tutorials with Travis CI, but I wanted to add my ros2 packages as well. Some are developed in Ubuntu, but others in Windows. I've also noticed that you use Jenkins. If it is easier, I'm glad to test there, of course

This kind of question is best asked on [ROS Answers](https://answers.ros.org) (if it is specific to ROS or ROS 2) or Stack Overflow and similar sites for generic questions about CI. The [ros_buildfarm](https://github.com/ros-infrastructure/ros_buildfarm) project doesn't currently support Windows CI. This repository contains our CI scripts and resources for running cross platform ROS 2 CI on Jenkins but it should be considered a very useful prototype for cross-platform expansion of ros_buildfarm rather than a stable or supported project on its own.
